// <auto-generated />
using System;
using MealPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlanner.Data.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260726204552_InitialCoreData")]
    partial class InitialCoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MealPlanner.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("CaloriesPer100")
                        .HasColumnType("REAL");

                    b.Property<int?>("CnfFoodCode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FiberPer100")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsNutritionEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServingWeightG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.IngredientPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreferredStore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PackageQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("PackageUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("IngredientId", "StoreId", "RecordedDate");

                    b.ToTable("IngredientPrices");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyFiberGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Superstore"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Safeway"
                        });
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.IngredientPrice", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Prices")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Store", "Store")
                        .WithMany("Prices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Store", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
