// <auto-generated />
using System;
using MealPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPlanner.Data.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260727021950_AddFoodCategoriesAndCombos")]
    partial class AddFoodCategoriesAndCombos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MealPlanner.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.DayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId", "Date")
                        .IsUnique();

                    b.ToTable("DayPlans");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("CaloriesPer100")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsPer100")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CnfFoodCode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FatPer100")
                        .HasColumnType("REAL");

                    b.Property<double>("FiberPer100")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsNutritionEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100")
                        .HasColumnType("REAL");

                    b.Property<double?>("ServingWeightG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.IngredientPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreferredStore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PackageQuantity")
                        .HasColumnType("REAL");

                    b.Property<string>("PackageUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("IngredientId", "StoreId", "RecordedDate");

                    b.ToTable("IngredientPrices");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarbohydrateIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProteinIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VegetableIngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarbohydrateIngredientId");

                    b.HasIndex("ProteinIngredientId");

                    b.HasIndex("VegetableIngredientId");

                    b.ToTable("MealCombos");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("QuantityOnHand")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "Location");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyCarbGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyFatGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyFiberGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyProteinGoal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.PlannedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MealComboId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealComboId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("DayPlanId", "Slot");

                    b.ToTable("PlannedMeals");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Costco"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Superstore"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Safeway"
                        });
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.DayPlan", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Days")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.IngredientPrice", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Prices")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Store", "Store")
                        .WithMany("Prices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealCombo", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "CarbohydrateIngredient")
                        .WithMany()
                        .HasForeignKey("CarbohydrateIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "ProteinIngredient")
                        .WithMany()
                        .HasForeignKey("ProteinIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "VegetableIngredient")
                        .WithMany()
                        .HasForeignKey("VegetableIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarbohydrateIngredient");

                    b.Navigation("ProteinIngredient");

                    b.Navigation("VegetableIngredient");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.PantryItem", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.PlannedMeal", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.DayPlan", "DayPlan")
                        .WithMany("Meals")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.MealCombo", "MealCombo")
                        .WithMany()
                        .HasForeignKey("MealComboId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPlanner.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DayPlan");

                    b.Navigation("MealCombo");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MealPlanner.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.DayPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MealPlanner.Domain.Entities.Store", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
