namespace MealPlanner.ServiceDefaults.Authorization;

/// <summary>
/// Custom claim types used throughout the MealPlanner application for user identification.
/// </summary>
public static class MealPlannerClaimTypes
{
    /// <summary>
    /// The claim type that carries the database identifier (<see cref="int"/>) of the authenticated
    /// <c>AppUser</c> record. Included in JWT tokens generated by the Web project and consumed by
    /// the API for per-user data filtering.
    /// </summary>
    public const string AppUserId = "app_user_id";
}
